### ISSUE TITLE
Build failure linking libgnuradio-core

### ISSUE THREAD

**Issue by rfb** [titanous/homebrew-gnuradio#11]
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/microtune_xxxx.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/ppio_ppdev.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gri_wavfile.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_file_sink.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_file_sink_base.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_file_source.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_file_descriptor_sink.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_file_descriptor_source.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_message_sink.cc.o
[ 61%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_message_source.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/microtune_xxxx_eval_board.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/microtune_4702_eval_board.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/microtune_4937_eval_board.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/ppio.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/sdr_1000.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_udp_sink.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_udp_source.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_wavfile_source.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_wavfile_sink.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/gr_tagged_file_sink.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/hier/gr_channel_model.cc.o
[ 62%] Building CXX object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/bug_work_around_6.cc.o
Linking CXX shared library libgnuradio-core.dylib
[ 65%] Built target gnuradio-core
make: **\* [all] Error 2
==> Build Environment
HOMEBREW_VERSION: 0.9.2
HEAD: 22527936a30bb622aaf553dbf9da176005808634
CPU: quad-core 64-bit sandybridge
OS X: 10.7.4-x86_64
Xcode: 4.4.1
CLT: 1.0.0.9000000000.1.1249367152
X11: 2.6.4 in /usr/X11
CC: /usr/bin/llvm-gcc => /usr/llvm-gcc-4.2/bin/llvm-gcc-4.2
CXX: /usr/bin/llvm-g++ => /usr/llvm-gcc-4.2/bin/llvm-g++-4.2
LD: /usr/bin/llvm-gcc => /usr/llvm-gcc-4.2/bin/llvm-gcc-4.2
CFLAGS: -Os -w -pipe -mmacosx-version-min=10.7 -march=core2 -msse4
CXXFLAGS: -Os -w -pipe -mmacosx-version-min=10.7 -march=core2 -msse4
CPPFLAGS: -I/usr/local/Cellar/cairo/1.12.2/include -I/usr/local/Cellar/pixman/0.26.2/include -I/usr/local/Cellar/libffi/3.0.11/include -I/usr/local/Cellar/gettext/0.18.1.1/include -I/usr/local/Cellar/readline/6.2.4/include -I/usr/X11/include
LDFLAGS: -L/usr/local/Cellar/cairo/1.12.2/lib -L/usr/local/Cellar/pixman/0.26.2/lib -L/usr/local/Cellar/libffi/3.0.11/lib -L/usr/local/Cellar/gettext/0.18.1.1/lib -L/usr/local/Cellar/readline/6.2.4/lib -L/usr/local/lib -L/usr/X11/lib
CMAKE_PREFIX_PATH: /usr/X11
MAKEFLAGS: -j4
MACOSX_DEPLOYMENT_TARGET: 10.7
PKG_CONFIG_PATH: /usr/local/Cellar/cairo/1.12.2/lib/pkgconfig:/usr/local/Cellar/pixman/0.26.2/lib/pkgconfig:/usr/local/Cellar/libffi/3.0.11/lib/pkgconfig:/usr/X11/share/pkgconfig:/usr/X11/lib/pkgconfig
ACLOCAL_PATH: /usr/local/Cellar/gettext/0.18.1.1/share/aclocal
OBJC: /usr/bin/llvm-gcc
PATH: /usr/local/Cellar/cairo/1.12.2/bin:/usr/local/Cellar/pixman/0.26.2/bin:/usr/local/Cellar/libffi/3.0.11/bin:/usr/local/Cellar/gettext/0.18.1.1/bin:/usr/local/Cellar/readline/6.2.4/bin:/usr/X11/bin:/Users/rfb/.rbenv/shims:/usr/local/share/python:/Users/rfb/.rbenv/bin:/Users/rfb/.rbenv/shims:/Users/rfb/sdk/air/bin::/Users/rfb/sdk/flex/bin:/Users/rfb/sdk/android/tools:/Users/rfb/sdk/android/platform-tools:/usr/local/git/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11/bin:/usr/local/Library/Contributions/cmds

**Comment by rfb** [comment]
re-brewed python, the Framework wasn't installed. Thanks for the recipe!

**Comment by mmichie** [comment]
Hrrm, I'm having this same issue, tried to rebrew python to no avail.  Any other tips?
