### ISSUE TITLE
scipy requires swig, but is not smart enough to know about it, so you need to explicity install it first

### ISSUE THREAD

**Issue by davidbuzz** [titanous/homebrew-gnuradio#2]
swig: scipy/sparse/linalg/dsolve/umfpack/umfpack.i

swig -python -I/usr/local/include -o build/src.macosx-10.7-intel-2.7/scipy/sparse/linalg/dsolve/umfpack/_umfpack_wrap.c -outdir build/src.macosx-10.7-intel-2.7/scipy/sparse/linalg/dsolve/umfpack scipy/sparse/linalg/dsolve/umfpack/umfpack.i

unable to execute swig: No such file or directory

error: command 'swig' failed with exit status 1

**Comment by davidbuzz** [comment]
solution:    "brew install swig"   ( which also installs pcre ) :-)

**Comment by titanous** [comment]
Added to the README. Thanks!
