### ISSUE TITLE
issue when installing matplotlib

### ISSUE THREAD

**Issue by diogoalves** [titanous/homebrew-gnuradio#3]
everthing seems to be ok until the matplotlib
in:
sudo easy_install pip
sudo pip install Cheetah lxml numpy scipy matplotlib

after first fail, I tried
sudo easy_install matplotlib

Tested on lion 10.7.4 xcode 4.3.2 and 4.3.3

Log from easy install

Searching for matplotlib
Reading http://pypi.python.org/simple/matplotlib/
Reading http://matplotlib.sourceforge.net
Reading https://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.0
Reading https://sourceforge.net/project/showfiles.php?group_id=80706&package_id=278194
Reading http://sourceforge.net/project/showfiles.php?group_id=80706&package_id=82474
Reading https://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-0.99.1/
Reading https://sourceforge.net/project/showfiles.php?group_id=80706&package_id=82474
Reading http://sourceforge.net/project/showfiles.php?group_id=80706
Reading https://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-0.99.3/
Reading http://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.1.0/
Reading https://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.0.1/
Best match: matplotlib 1.1.0
Downloading http://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.1.0/matplotlib-1.1.0.tar.gz/download
Processing matplotlib-1.1.0.tar.gz
Running matplotlib-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8f72kB/matplotlib-1.1.0/egg-dist-tmp-Da2qnm
# basedirlist is: []

BUILDING MATPLOTLIB
            matplotlib: 1.1.0
                python: 2.7.1 (r271:86832, Jul 31 2011, 19:30:53)  [GCC
                        4.2.1 (Based on Apple Inc. build 5658) (LLVM build
                        2335.15.00)]
              platform: darwin

REQUIRED DEPENDENCIES
                 numpy: 1.5.1
             freetype2: found, but unknown version (no pkg-config)
                        \* WARNING: Could not find 'freetype2' headers in any
                        \* of '.', './freetype2'.

OPTIONAL BACKEND DEPENDENCIES
                libpng: found, but unknown version (no pkg-config)
                        \* Could not find 'libpng' headers in any of '.'
               Tkinter: Tkinter: 81008, Tk: 8.5, Tcl: 8.5
                  Gtk+: no
                        \* Building for Gtk+ requires pygtk; you must be able
                        \* to "import gtk" in your build/install environment
       Mac OS X native: yes
                    Qt: no
                   Qt4: no
                 Cairo: no

OPTIONAL DATE/TIMEZONE DEPENDENCIES
              datetime: present, version unknown
              dateutil: 1.5
                  pytz: matplotlib will provide
adding pytz

OPTIONAL USETEX DEPENDENCIES
                dvipng: no
           ghostscript: /bin/sh: gs: command not found
                 latex: no
# [Edit setup.cfg to suppress the above messages]

pymods ['pylab']
packages ['matplotlib', 'matplotlib.backends', 'matplotlib.backends.qt4_editor', 'matplotlib.projections', 'matplotlib.testing', 'matplotlib.testing.jpl_units', 'matplotlib.tests', 'mpl_toolkits', 'mpl_toolkits.mplot3d', 'mpl_toolkits.axes_grid', 'mpl_toolkits.axes_grid1', 'mpl_toolkits.axisartist', 'matplotlib.sphinxext', 'matplotlib.tri', 'matplotlib.delaunay', 'pytz']
warning: no files found matching 'KNOWN_BUGS'
warning: no files found matching 'INTERACTIVE'
warning: no files found matching 'MANIFEST'
warning: no files found matching '**init**.py'
warning: no files found matching 'examples/data/_'
warning: no files found matching 'lib/mpl_toolkits'
warning: no files found matching 'LICENSE_' under directory 'license'
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from src/ft2font.cpp:3:
src/ft2font.h:16:22: error: ft2build.h: No such file or directory
src/ft2font.h:17:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:18:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:19:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:20:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:21:10: error: #include expects "FILENAME" or <FILENAME>
In file included from src/ft2font.cpp:3:
src/ft2font.h:35: error: ‘FT_Bitmap’ has not been declared
src/ft2font.h:35: error: ‘FT_Int’ has not been declared
src/ft2font.h:35: error: ‘FT_Int’ has not been declared
src/ft2font.h:91: error: expected ‘,’ or ‘...’ before ‘&’ token
src/ft2font.h:91: error: ISO C++ forbids declaration of ‘FT_Face’ with no type
src/ft2font.h:138: error: ‘FT_Face’ does not name a type
src/ft2font.h:139: error: ‘FT_Matrix’ does not name a type
src/ft2font.h:140: error: ‘FT_Vector’ does not name a type
src/ft2font.h:141: error: ‘FT_Error’ does not name a type
src/ft2font.h:142: error: ‘FT_Glyph’ was not declared in this scope
src/ft2font.h:142: error: template argument 1 is invalid
src/ft2font.h:142: error: template argument 2 is invalid
src/ft2font.h:143: error: ‘FT_Vector’ was not declared in this scope
src/ft2font.h:143: error: template argument 1 is invalid
src/ft2font.h:143: error: template argument 2 is invalid
src/ft2font.h:149: error: ‘FT_BBox’ does not name a type
src/ft2font.cpp:51: error: ‘FT_Library’ does not name a type
src/ft2font.cpp:114: error: variable or field ‘draw_bitmap’ declared void
src/ft2font.cpp:114: error: ‘FT_Bitmap’ was not declared in this scope
src/ft2font.cpp:114: error: ‘bitmap’ was not declared in this scope
src/ft2font.cpp:115: error: ‘FT_Int’ was not declared in this scope
src/ft2font.cpp:116: error: ‘FT_Int’ was not declared in this scope
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/__multiarray_api.h:1187: warning: ‘int _import_array()’ defined but not used
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from src/ft2font.cpp:3:
src/ft2font.h:16:22: error: ft2build.h: No such file or directory
src/ft2font.h:17:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:18:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:19:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:20:10: error: #include expects "FILENAME" or <FILENAME>
src/ft2font.h:21:10: error: #include expects "FILENAME" or <FILENAME>
In file included from src/ft2font.cpp:3:
src/ft2font.h:35: error: ‘FT_Bitmap’ has not been declared
src/ft2font.h:35: error: ‘FT_Int’ has not been declared
src/ft2font.h:35: error: ‘FT_Int’ has not been declared
src/ft2font.h: In member function ‘unsigned int FT2Image::get_width() const’:
src/ft2font.h:44: warning: implicit conversion shortens 64-bit value into a 32-bit value
src/ft2font.h: In member function ‘unsigned int FT2Image::get_height() const’:
src/ft2font.h:48: warning: implicit conversion shortens 64-bit value into a 32-bit value
src/ft2font.h: At global scope:
src/ft2font.h:91: error: expected ‘,’ or ‘...’ before ‘&’ token
src/ft2font.h:91: error: ISO C++ forbids declaration of ‘FT_Face’ with no type
src/ft2font.h:138: error: ‘FT_Face’ does not name a type
src/ft2font.h:139: error: ‘FT_Matrix’ does not name a type
src/ft2font.h:140: error: ‘FT_Vector’ does not name a type
src/ft2font.h:141: error: ‘FT_Error’ does not name a type
src/ft2font.h:142: error: ‘FT_Glyph’ was not declared in this scope
src/ft2font.h:142: error: template argument 1 is invalid
src/ft2font.h:142: error: template argument 2 is invalid
src/ft2font.h:143: error: ‘FT_Vector’ was not declared in this scope
src/ft2font.h:143: error: template argument 1 is invalid
src/ft2font.h:143: error: template argument 2 is invalid
src/ft2font.h:149: error: ‘FT_BBox’ does not name a type
src/ft2font.cpp:51: error: ‘FT_Library’ does not name a type
src/ft2font.cpp:114: error: variable or field ‘draw_bitmap’ declared void
src/ft2font.cpp:114: error: ‘FT_Bitmap’ was not declared in this scope
src/ft2font.cpp:114: error: ‘bitmap’ was not declared in this scope
src/ft2font.cpp:115: error: ‘FT_Int’ was not declared in this scope
src/ft2font.cpp:116: error: ‘FT_Int’ was not declared in this scope
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/__multiarray_api.h:1187: warning: ‘int _import_array()’ defined but not used
lipo: can't open input file: /var/tmp//cczMmJZI.out (No such file or directory)
error: Setup script exited with error: command 'llvm-gcc-4.2' failed with exit status 1

**Comment by titanous** [comment]
I've updated the readme to use the Homebrew Python and some compiler flags, the combination fixes this issue for me.
