### ISSUE TITLE
Trying to install gnu-radio

### ISSUE THREAD

**Issue by sbfreddie** [titanous/homebrew-gnuradio#4]
While following the instructions for the installation of gnu-radio all went well until I tried to in actually install gnu radio.
The code:
brew install gnuradio --with-qt
Failed with this error:
Unsatisfied dependency: Cheetah
Homebrew does not provide Python dependencies; install with:
  easy_install Cheetah

So I tried:
easy_install Cheetah

Which returns:
Searching for Cheetah
Best match: Cheetah 2.4.4
Adding Cheetah 2.4.4 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Processing dependencies for Cheetah
Finished processing dependencies for Cheetah

So I tried again and the same thing happens:
brew install gnuradio --with-qt

Which returns:
Unsatisfied dependency: Cheetah
Homebrew does not provide Python dependencies; install with:
  easy_install Cheetah
Error: An unsatisfied requirement failed this build.

Here are the systems specifics:
==> Build Environment
HOMEBREW_VERSION: 0.9.2
HEAD: dcb27995fd39c388e86e8b589756737cf3882e9a
CPU: quad-core 64-bit core2
OS X: 10.7.4-i386
Xcode: 4.4 => 
CLT: 1.0.0.9000000000.1.1249367152
X11: XQuartz 2.7.2_beta3 in /opt/X11
CC: /usr/bin/clang
CXX: /usr/bin/clang++ => /usr/bin/clang
LD: /usr/bin/clang
CFLAGS: -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7
CXXFLAGS: -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7
CPPFLAGS: -I/usr/local/Cellar/cairo/1.12.2/include -I/usr/local/Cellar/pixman/0.26.2/include -I/usr/local/Cellar/libffi/3.0.11/include -I/usr/local/Cellar/gettext/0.18.1.1/include -isystem /usr/local/include
LDFLAGS: -L/usr/local/Cellar/cairo/1.12.2/lib -L/usr/local/Cellar/pixman/0.26.2/lib -L/usr/local/Cellar/libffi/3.0.11/lib -L/usr/local/Cellar/gettext/0.18.1.1/lib -L/usr/local/lib
MAKEFLAGS: -j4
MACOSX_DEPLOYMENT_TARGET: 10.7
PKG_CONFIG_PATH: /usr/local/Cellar/cairo/1.12.2/lib/pkgconfig:/usr/local/Cellar/pixman/0.26.2/lib/pkgconfig:/usr/local/Cellar/libffi/3.0.11/lib/pkgconfig
ACLOCAL_PATH: /usr/local/Cellar/gettext/0.18.1.1/share/aclocal
OBJC: /usr/bin/clang
PATH: /usr/local/Cellar/cairo/1.12.2/bin:/usr/local/Cellar/pixman/0.26.2/bin:/usr/local/Cellar/libffi/3.0.11/bin:/usr/local/Cellar/gettext/0.18.1.1/bin:/usr/local/sbin:/usr/local/share/python:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/avr/bin:/usr/texbin:/usr/local/Library/Contributions/cmds

Error: Failed executing: cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.1 -DQWT_INCLUDE_DIRS=/usr/local/lib/qwt.framework/Headers -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnuradio/3.6.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -Wno-dev -DENABLE_GR_QTGUI=OFF -DENABLE_DOXYGEN=OFF (gnuradio.rb:49)

Any Clue what to do next?

**Comment by titanous** [comment]
Did you follow the instructions to run this command?

```
pip install Cheetah lxml scipy
```

**Comment by sbfreddie** [comment]
Jonathan:
Yes I did, and here are the results:
pip install Cheetah lxml scipy

Successfully installed Cheetah lxml scipy Markdown

I even tried it again just to make sure, but all was OK with "Cheetah lxml scipy"

Thanks,
Freddie

**Comment by sbfreddie** [comment]
Jonathan:
I fixed the problem by making sure /usr/local/bin was first in my PATH.  I suggest you make a note in your instructions to make sure this is the case otherwise the system will try to use the python in /usr/bin which is the reason for the failure.

**Comment by titanous** [comment]
Ah, I assumed that everyone who has homebrew installed has their PATH setup properly. I'll make a note of it.
