### ISSUE TITLE
Still trying to install gnuradio

### ISSUE THREAD

**Issue by sbfreddie** [titanous/homebrew-gnuradio#5]
Jonathan:
This is something new that I have come across, two errors in the build process at 42% into the make.
This is the display:

[ 42%] Building C object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/filter/float_dotprod_sse64.S.o
[ 42%] /tmp/homebrew-gnuradio-3.6.1-DcYi/gnuradio-3.6.1/gnuradio-core/src/lib/filter/float_dotprod_sse64.S:57:2: error: unknown directive
 .version "01.01"
 ^
make[2]: **\* [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/filter/float_dotprod_sse64.S.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
Building C object gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/filter/float_dotprod_3dnow64.S.o
/tmp/homebrew-gnuradio-3.6.1-DcYi/gnuradio-3.6.1/gnuradio-core/src/lib/filter/float_dotprod_3dnow64.S:57:2: error: unknown directive
 .version "01.01"
 ^
make[2]: **\* [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/filter/float_dotprod_3dnow64.S.o] Error 1
make[1]: **\* [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/all] Error 2
make: **\* [all] Error 2
==> Build Environment
HOMEBREW_VERSION: 0.9.2
HEAD: dcb27995fd39c388e86e8b589756737cf3882e9a
CPU: quad-core 64-bit core2
OS X: 10.7.4-i386
Xcode: 4.4 => 
CLT: 1.0.0.9000000000.1.1249367152
X11: XQuartz 2.7.2_beta3 in /opt/X11
CC: /usr/bin/clang
CXX: /usr/bin/clang++ => /usr/bin/clang
LD: /usr/bin/clang
CFLAGS: -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7
CXXFLAGS: -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7
CPPFLAGS: -I/usr/local/Cellar/cairo/1.12.2/include -I/usr/local/Cellar/pixman/0.26.2/include -I/usr/local/Cellar/libffi/3.0.11/include -I/usr/local/Cellar/gettext/0.18.1.1/include -isystem /usr/local/include
LDFLAGS: -L/usr/local/Cellar/cairo/1.12.2/lib -L/usr/local/Cellar/pixman/0.26.2/lib -L/usr/local/Cellar/libffi/3.0.11/lib -L/usr/local/Cellar/gettext/0.18.1.1/lib -L/usr/local/lib
MAKEFLAGS: -j4
MACOSX_DEPLOYMENT_TARGET: 10.7
PKG_CONFIG_PATH: /usr/local/Cellar/cairo/1.12.2/lib/pkgconfig:/usr/local/Cellar/pixman/0.26.2/lib/pkgconfig:/usr/local/Cellar/libffi/3.0.11/lib/pkgconfig
ACLOCAL_PATH: /usr/local/Cellar/gettext/0.18.1.1/share/aclocal
OBJC: /usr/bin/clang
PATH: /usr/local/Cellar/cairo/1.12.2/bin:/usr/local/Cellar/pixman/0.26.2/bin:/usr/local/Cellar/libffi/3.0.11/bin:/usr/local/Cellar/gettext/0.18.1.1/bin:/usr/local/share/python:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin::/usr/local/Library/Contributions/cmds

Error: Failed executing: make (gnuradio.rb:50)

This link will help resolve the above errors:
    https://github.com/titanous/homebrew-gnuradio/issues/new

Any thought on a solution?

Thanks,
Freddie

**Comment by sbfreddie** [comment]
Jonathan:
I solved the above problem by using the --use-llvm option.  It appears the clang assembler doesn't work correctly on the .S files.
All is well now

**Comment by titanous** [comment]
Thanks, I'll update the build.

**Comment by titanous** [comment]
Can you tell me what the output of `clang -v` on your system is?

**Comment by sbfreddie** [comment]
Jonathan:
This is the output of clang -v:
Apple clang version 4.0 (tags/Apple/clang-421.0.60) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.0
Thread model: posix

**Comment by titanous** [comment]
Thanks, I'll bump the clang failure version in the recipe.
