### ISSUE TITLE
Fatal Python error: Interpreter not initialized (version mismatch?)

### ISSUE THREAD

**Issue by sbfreddie** [titanous/homebrew-gnuradio#6]
Jonathan:

Whenever I try to use anything that uses Python I get this error:
Fatal Python error: Interpreter not initialized (version mismatch?) Abort trap 6

What have I done wrong?
Any help would be appreciated.

Thanks,
Freddie

**Comment by titanous** [comment]
I'm not really sure. Do you have the homebrew python in your PATH and PYTHONPATH?. What's the output of `which python` and `python --version`?

**Comment by sbfreddie** [comment]
Jonathan:
The output of which python is:
/usr/bin/python
The output of python --version is:
Python 2.7.1

Here is the output of env:
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/rb/y3bt7gq151x05xlwpzpzc0hm0000gt/T/
Apple_PubSub_Socket_Render=/tmp/launch-y6LBcQ/Render
TERM_PROGRAM_VERSION=303.2
TERM_SESSION_ID=7C675DD7-C0EB-400A-A3DC-DA34F7244670
USER=freddie
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/tmp/launch-ytkSpp/Listeners
Apple_Ubiquity_Message=/tmp/launch-n8tJ7F/Apple_Ubiquity_Message
__CF_USER_TEXT_ENCODING=0x1FA:0:0
PATH=/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/local/share/python:/bin:/sbin:/usr/bin:/usr/sbin
PWD=/Users/freddie/bin
LANG=en_US.UTF-8
DYLD_FRAMEWORK_PATH=/usr/local/lib:
HOME=/Users/freddie
SHLVL=1
LOGNAME=freddie
PYTHONPATH=/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages
DISPLAY=/tmp/launch-RntsXF/org.macosforge.xquartz:0
_=/usr/bin/env

As you can see the PATH variable points to /usr/local/bin before the system paths.
Is there some way to tell the system to use a different python than the systems?

Thanks,
Freddie

**Comment by titanous** [comment]
The first item in your PATH is `/Library/Frameworks/Python.framework/Versions/2.7/bin` which likely contains a `python` binary or a symlink to `/usr/bin/python`.

**Comment by sbfreddie** [comment]
This is strange.
When I look in /usr/local/bin for the symlinks to python they appear to be there but when you ask for the finder to "Show Original" it comes up with nothing!  In fact all the symlinks for python are there but dead.

Any Ideas?

Thanks,
Freddie

**Comment by titanous** [comment]
Try a `brew unlink python` and then `brew link python`. If that doesn't work, `brew uninstall python` and `brew install python --framework`.

**Comment by sbfreddie** [comment]
I'll give it a shot.

**Comment by sbfreddie** [comment]
Well it looks like the links are now working.

thanks,
Freddie

**Comment by sbfreddie** [comment]
Still some strangeness, if I ask which python it responds with:
/usr/local/bin/python
Which is correct, but if I ask which python version it responds with:
Python 2.7.1
Which is not the installed version, its the system version.

Ideas?
Thanks,
Freddie

**Comment by titanous** [comment]
Dumb question: have you reloaded your shell since fixing the symlinks? It could be a cached PATH.

**Comment by sbfreddie** [comment]
Not a dumb question, a dumb person (me).
That gives the right answer.

Now lets see what happens.

**Comment by sbfreddie** [comment]
Well, when I issue this command:
gnuradio-companion
I still get the famed message:
Fatal Python error: Interpreter not initialized (version mismatch?)

Does this mean I have to start over?

Thanks,
Freddie

**Comment by titanous** [comment]
I'd suggest uninstalling and recompiling gnuradio. No guarantees that it will work though, I've been having trouble getting it running on Mountain Lion with the latest Xcode (different python crash).

**Comment by sbfreddie** [comment]
I'm going to write a script for this so I can just watch it go.  It takes a couple of hours to build all of these programs and libs.
I have dumped /usr/local in the trash after uninstalling HomeBrew a least three times in the last three days.  And start all over again.  I have found some hints searching the net with this error:
Fatal Python error: Interpreter not initialized (version mismatch?)

Looks like i'm not the only one to have this problem

Thanks,
Freddie

**Comment by c1de0x** [comment]
On Mountain Lion, I'm getting:

$ gnuradio-companion
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Fatal Python error: PyThreadState_Get: no current thread

Possibly a lib-path error?

**Comment by titanous** [comment]
Yeah, I'm getting that on Mountain Lion as well. It feels like an upstream issue, but I'm going to try compiling it with GCC just in case.

**Comment by c1de0x** [comment]
looks like something hinky might be going on:

$ DYLD_PRINT_LIBRARIES=1 gnuradio-companion 2>&1 | grep -i python | grep -v Cellar
dyld: loaded: /usr/local/bin/python
dyld: loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
Fatal Python error: PyThreadState_Get: no current thread

**Comment by titanous** [comment]
Interesting. That second python should definitely not be there.

**Comment by c1de0x** [comment]
That was my thought. I didn't really take anything like a closer look ;)

**Comment by titanous** [comment]
@c1de0x: can you open another issue about this? I think this is a completely different problem.

**Comment by c1de0x** [comment]
erm. ok. Issue #7 opened

**Comment by titanous** [comment]
@sbfreddie I just pushed a patch that fixes the Mountain Lion python issue, can you do a `brew update` and see if it fixes your issue as well?

**Comment by sbfreddie** [comment]
Jonathan:
I tried your new fix, however the line:
pip install numpy Cheetah lxml https://github.com/scipy/scipy/tarball/v0.11.0rc2 http://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.1.1/matplotlib-1.1.1.tar.gz

Does not work for me, it tries to install scipy and ignores bumpy Cheetah and lxml and then dies.

I went back to the original installing first numpy, then Cheetah and lxml, then scipy by itself and then matplotlib by itself.

Now the Fatal Python error is gone.

Thanks,
Freddie

**Comment by rfb** [comment]
I'm seeing the same version mismatch.

$ gnuradio-companion                                                                                                                                                    Fatal Python error: Interpreter not initialized (version mismatch?)
[1]    59514 abort      gnuradio-companion

DYLD_PRINT_LIBRARIES=1 gnuradio-companion 2>&1 | grep -i python | grep -v Cellar
dyld: loaded: /usr/local/bin/python
dyld: loaded: /usr/lib/libpython2.7.dylib
Fatal Python error: Interpreter not initialized (version mismatch?)

I've traced it down to loading the gnuradio Platform module.

$ python                                                                                                                                                                Python 2.7.3 (default, Aug 29 2012, 17:59:47) 
[GCC 4.2.1 Compatible Apple Clang 4.0 ((tags/Apple/clang-421.0.60))] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > from gnuradio.grc.python.Platform import Platform
> > > Fatal Python error: Interpreter not initialized (version mismatch?)

Any suggestions on where I could go from here?
