### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread (Mountain Lion)

### ISSUE THREAD

**Issue by c1de0x** [titanous/homebrew-gnuradio#7]
On Mountain Lion, I'm getting:

$ gnuradio-companion
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/init.py:57: GtkWarning: could not open display
warnings.warn(str(e), _gtk.Warning)
Fatal Python error: PyThreadState_Get: no current thread

Possibly a lib-path error?

$ DYLD_PRINT_LIBRARIES=1 gnuradio-companion 2>&1 | grep -i python | grep -v Cellar
dyld: loaded: /usr/local/bin/python
dyld: loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
Fatal Python error: PyThreadState_Get: no current thread

this is forked from Issue #6

**Comment by c1de0x** [comment]
$ uname -a
Darwin xyz.local 12.0.0 Darwin Kernel Version 12.0.0: Sun Jun 24 23:00:16 PDT 2012; root:xnu-2050.7.9~1/RELEASE_X86_64 x86_64
$ which python
/usr/local/bin/python
$ python --version
Python 2.7.3

$ gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

**Comment by titanous** [comment]
```
$ otool -L /usr/local/Cellar/gnuradio/3.6.1/lib/libgnuradio-qtgui.3.6.1.dylib 
/usr/local/Cellar/gnuradio/3.6.1/lib/libgnuradio-qtgui.3.6.1.dylib:
    /usr/local/lib/libgnuradio-qtgui.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    @loader_path/libgnuradio-core.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    /usr/local/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.2)
    /usr/local/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.2)
    /usr/local/lib/qwt.framework/Versions/6/qwt (compatibility version 6.0.0, current version 6.0.1)
    /System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.2)
    @loader_path/libgruel.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    /usr/local/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 56.0.0)
```

Indicates that it's linking against the system python. I'm looking into how to prevent that.

**Comment by titanous** [comment]
It looks like this `DYLD_FRAMEWORK_PATH` is needed: f9655d53cd7af2000f009f59cd4855e071df6952

I removed it because of this error message:

```
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
```

I'm looking into how to make it work again.

**Comment by titanous** [comment]
According to this, that's just a red herring: http://openradar.appspot.com/11894054

I'm trying to compile it with the path set correctly, we'll see how it goes.

**Comment by c1de0x** [comment]
ok ill test again when you push an update

**Comment by titanous** [comment]
You can actually test right now by running:

```
export DYLD_FRAMEWORK_PATH=/usr/local/lib:$DYLD_FRAMEWORK_PATH
brew uninstall gnuradio
brew install gnuradio
```

**Comment by c1de0x** [comment]
nope. still borked

$ otool -L /usr/local/Cellar/gnuradio/3.6.1/lib/libgnuradio-qtgui.3.6.1.dylib 
/usr/local/Cellar/gnuradio/3.6.1/lib/libgnuradio-qtgui.3.6.1.dylib:
    /usr/local/lib/libgnuradio-qtgui.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    @loader_path/libgnuradio-core.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    /usr/local/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.2)
    /usr/local/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.2)
    /usr/local/lib/qwt.framework/Versions/6/qwt (compatibility version 6.0.0, current version 6.0.1)
    /System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.2)
    @loader_path/libgruel.3.6.1.dylib (compatibility version 3.6.1, current version 0.0.0)
    /usr/local/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 56.0.0)

**Comment by titanous** [comment]
I just pushed a patch that fixes this issue. Can you test it out?

```
brew update
brew uninstall gnuradio
brew install gnuradio
```

**Comment by c1de0x** [comment]
Now I get a segfault:
 gnuradio-companion/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Segmentation fault: 11

**Comment by titanous** [comment]
Do you have [XQuartz](http://xquartz.macosforge.org/trac/wiki) installed?

**Comment by c1de0x** [comment]
Yes. XQuartz 2.7.2

**Comment by grmrgecko** [comment]
From the looks of it, this looks to be an issue where GNURadio is compiling against OSX's python install.

Looking further it seems cairo is causing the crash. Uninstalled everything I installed to manually build GNU Radio with Mac OS X Python and re-installing it.

**Comment by grmrgecko** [comment]
brew uninstall cairo py2cairo pygobject pygtk gtk+ gnuradio

brew install pygtk gnuradio

That fixed it for me as I installed the other packages before I installed python via brew..

**Comment by lokkju** [comment]
I'm still getting this - using a little tool I wrote that tells you which dylibs are using the system python ( https://gist.github.com/4466116 ), I found that /usr/local/lib/python2.7/site-packages/gnuradio/qtgui/_qtgui_swig.so was linked against the System python.

I tried removing both swig and gnuradio and reinstalling - but with no luck.

Ideas?

**Comment by zacmanchester** [comment]
I had the same problem. I got around it by temporarily symlinking the brewed python in place of the system python, brew uninstall gnuradio, brew install gnuradio, then changing the symlinks back.

**Comment by 1am** [comment]
I know the issue is closed, but just for reference I've had a simillar issue today. What helped me was following what tomekr did in https://github.com/metacollin/homebrew-gnuradio/issues/47#issuecomment-134437742
